In [ ]:
#API and JSON payloads practice.
import requests as req
import pandas as pd
while True:
    x = req.get("https://api.nal.usda.gov/fdc/v1/foods/list?pageSize=200&pageNumber=5&api_key=zCnC2oSh6DxPXS1w1KtQGMchMHmb0sB4VOgOaN3P")
    print(x)
x = x.json()

def requestAllFood():
    pageNum=1
    foods = []
    while True:
        url = 'https://api.nal.usda.gov/fdc/v1/foods/list?pageSize=200&api_key=zCnC2oSh6DxPXS1w1KtQGMchMHmb0sB4VOgOaN3P'+ '&pageNumber='+str(pageNum)
        requests=req.get(url)
        if not requests.ok:
            break
        foods = foods+req.json()
        pageNum = pageNum+1
        print(pageNum)
    return foods

df = pd.DataFrame(x)

In [ ]:
len(x)

In [ ]:

#df.drop(df.columns[[0,2,3,4,6]],axis="columns",inplace=True)
df.head

In [1]:
import pandas as pd
df=pd.read_csv("iron.csv")
df.drop(df.columns[[1,2,3]],axis="columns",inplace=True)
df = df.drop(321074) #DROPPING Mint chocolate sticks, since it is most likely they are not calculated correctly.
df.sort_values(by="value", inplace=True, ascending=False)

#df = df[~df.foodDescription.str.contains("baby|Baby|BABY")] #used to drop rows that have specific strings.
df.head(10)
#value and measureValue are measured in mg
#"value" is iron per foodMeasure.   --- use this as main data point as it compares all foods using 100 grams of each.
#foodWeight is serving size measured in valueUnit.
#measureValue is iron per foodWeight.

C:\Users\mdzhalolov\AppData\Local\Temp\ipykernel_18032\3696426461.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("iron.csv")

,fdcId,foodDescription,value,foodWeight,valueUnit,foodMeasure,measureValue
223005,1983528,GARLIC SALT,250000.0,1.2,g,100 g,3000.0
320235,1133950,TAHINI SESAME SEED PASTE,35700.0,28.0,g,100 g,10000.0
197298,1896769,TAMARI LITE 50% LESS SODIUM GLUTEN FREE SOY SA...,35300.0,17.0,g,100 g,6000.0
131467,2107654,"DATU PUTI, SOY SAUCE",26700.0,15.0,ml,100 g,4000.0
169875,2157057,CHIPOTLE SEASONING,25000.0,4.0,g,100 g,1000.0
249917,1983386,"HILCO, DESPICABLE ME CHARACTER MUG COCOA SET",19000.0,21.0,g,100 g,4000.0
303239,1742558,PSYLLIUM HUSK POWDER,16700.0,9.0,g,100 g,1500.0
224474,1851789,"NATURAL ALOE POWDERED DRINK MIX, STRAWBERRY-KIWI",14300.0,7.0,g,100 g,1000.0
224471,1983520,"NATURAL ALOE POWDERED DRINK MIX, POMEGRANATE",14300.0,7.0,g,100 g,1000.0
165788,2122848,CORN CEREAL FROSTED FLAKES,14200.0,38.0,g,100 g,5400.0

In [ ]:
import seaborn as sb
import matplotlib.pyplot as plt
yAxis= df.head(10).foodDescription.values.tolist()
xAxis= df.head(10).value.values.tolist()
#plt.xticks(rotation=45) - used to rotate labels if needed.
#plt.xlabel("Iron Content in mg per 100g")
#plt.ylabel("Food Items")
#plt.title("Top 10 Food Items with the most Iron content per 100g")
#sb.barplot(x=xAxis,y=yAxis)
sb.histplot(x=df["value"])